### ISSUE TITLE
Unable to travel

### ISSUE THREAD

**Issue by wyrren** [TitanNano/TS4ControlAnySim#8] opened 2019-11-07 05:37 UTC
I'm trying to travel with one sim (in a family of 6) from forgotten hallow to glimmerbrook. It's giving me an error 109 and I took a look in my sims4 folder to find a bunch of LEs. Your mod was working fine for me at the original lot as I had added 2 sims to test it out.  I then unselected them after they left the lot (before trying to travel). I have no idea how to read LE reports, so I don't know what's going on. I'll just add them for you, so I hope it helps! I'm going to uninstall this mod sadly, but I would love to try it again after an update. It was very fun to use. :)
[lastUIException_63708786601.txt](https://github.com/TitanNano/TS4ControlAnySim/files/3818000/lastUIException_63708786601.txt)
[lastException.txt](https://github.com/TitanNano/TS4ControlAnySim/files/3818001/lastException.txt)
[lastException_63708786601.txt](https://github.com/TitanNano/TS4ControlAnySim/files/3818003/lastException_63708786601.txt)

**Comment by TitanNano** [comment] 2019-11-07 08:24
I can see what the problem is, thanks for the report. Which lot did you travel to? The exception tells me there is a household on the target lot, but there are no sims in the household. I can fix this, but wonder how this comes to happen.

**Comment by wyrren** [comment] 2019-11-07 08:42
I was traveling to the closest lot to the magic portal. Not sure what it's called as I don't have the game open. (I do remember it is a 20x30 residential) And it doesn't have a household, true. Just some trees on it. I wonder how the guru's made that mistake. lol. Thanks for taking a look and replying so fast!

**Comment by TitanNano** [comment] 2019-11-07 22:42
@wyrren this issue should be fixed in this **preview version** https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.1.0-pre.1. Can you verify this?

**Comment by wyrren** [comment] 2019-11-08 00:17
It worked, thank you! The same lot loaded this time with no problems. Great work!

**Closed** 2019-11-08 08:35 UTC
Labels: bug
