### ISSUE TITLE
removing selectable sims can cause UI Exception

### ISSUE THREAD

**Issue by RuralFPSGamer** [TitanNano/TS4ControlAnySim#20] opened 2019-11-26 13:48 UTC
Doesn't seem to affect the use of the mod, but this UI Exception is created occasionally because of it.
[lastUIException.txt](https://github.com/TitanNano/TS4ControlAnySim/files/3892098/lastUIException.txt)

**Comment by TitanNano** [comment] 2019-12-03 22:44
@RuralFPSGamer I got a report about this exception before, but am not able to reproduce it myself. Is this still occurring regularly?

**Comment by RuralFPSGamer** [comment] 2019-12-04 02:23
@TitanNano yeah it happens almost every time I use the mod to control a sim, but it doesn't seem to affect the gameplay any. I thought maybe it was just when I left the lot or shut down while still having control, but I also see it just controlling a sim for a moment to make them do something then stopping control.

**Comment by RuralFPSGamer** [comment] 2019-12-04 18:18
It might be pack related maybe? Unless you have all the packs.

**Comment by TitanNano** [comment] 2019-12-04 21:44
I have all the packs 😉️

**Comment by RuralFPSGamer** [comment] 2019-12-05 13:45
I finally got around to doing another test in a newly created game with only your mod in and no others. Same result. So at least I know it's not a conflict with something else. It's generated from your mod. Here's the latest one.
[lastUIException.txt](https://github.com/TitanNano/TS4ControlAnySim/files/3927089/lastUIException.txt)

**Comment by TitanNano** [comment] 2019-12-05 19:03
@TitanNano I see. Thanks for testing this. Did you by any chance notice when exactly the exception occurred? What did you do when the exception happend?

**Comment by RuralFPSGamer** [comment] 2019-12-06 00:53
I figured out why I was getting the UIException by playing the game in a window with the sims 4 folder open. The exception occurs if you leave the controlled sim active when selecting "Don't Control Sim" then switch away to another sim. The active window closing of the sim no longer being controlled causes the error. As long as you remember to switch away to another active user before clicking on the sim to stop controlling it, no error occurs.

**Comment by TitanNano** [comment] 2019-12-06 09:36
@RuralFPSGamer Awesome! Many thanks for figuring this out. This can be easily fixed.

**Comment by TitanNano** [comment] 2019-12-07 15:58
@RuralFPSGamer this issue should be fixed in the latest preview version https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-pre.2

**Comment by RuralFPSGamer** [comment] 2019-12-07 16:08
Confirmed. No longer an issue in the pre release version, thanks!

**Comment by TitanNano** [comment] 2020-03-20 23:36
This bug now can occur when a sim is released from control while currently controlling another sim. The game always tries to switch away from the active sim which sometimes means it switches to the sim being released. The active sim should only change if it is the subject of the release action.

**Comment by TitanNano** [comment] 2020-03-21 18:15
Has been verified as fixed.

**Closed by TitanNano** 2020-03-21 18:15 UTC
Labels: bug
