### ISSUE TITLE
Problem with "Control Any Sim" mod

### ISSUE THREAD

**Issue by Pattycake155** [TitanNano/TS4ControlAnySim#51] opened 2021-12-05 07:57 UTC
So I was playing sims but out of no where, whenever I tried to click on my sim or any sim the interaction menu (no menu would pop up at all) wouldn't show up...I tried restarting my game and nothing. So I did the 50-50 method to see what was causing my game to mess up, and it turned out to be the "ControlAnySim" mod. I love this mod so much and I was really upset that I can't use it... Using the mod impacted my gameplay so much. The mod NEEDS an update for sure and I wish to use it again without anything messing up. Please update.

**Comment by TitanNano** [comment] 2021-12-05 18:59
Very likely duplicate of #46.

**Closed by TitanNano** 2021-12-05 18:59 UTC
